import type { NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"
import Speech from "./speech"
import { SpeechType } from "../types/speech"

const Home: NextPage = (props: any) => {
  const [loading, setLoading] = useState<boolean>(false)
  const [speech, setSpeech] = useState<SpeechType[]>([
    {
      id: 0,
      type: "answer",
      text: "I'm all ears.",
    },
  ])
  const [fullSpeech, setFullSpeech] = useState<string>("")
  const [data, setData] = useState<any>([{
    title: "token OpenAI",
    value: "none",
  },
  // {
  //   title: "token ElevenLabs",
  //   value: "none",
  // }
  ])

  useEffect(() => {
    localStorage.setItem("data", JSON.stringify(data))
  }, [data])


  const dataEmpty = data.find((d: any) => d.title === "token OpenAI").value == "none" ? true : false as boolean

  const [showParams, setShowParams] = useState<boolean>(dataEmpty)

  useEffect(() => {
    if (dataEmpty) {
      setShowParams(true)
    }
  }, [showParams])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Speech
          speech={speech}
          loading={loading}
          fullSpeech={fullSpeech}
          data={data}
          setLoading={setLoading}
          setSpeech={setSpeech}
          setFullSpeech={setFullSpeech}
        />
    </>
  )
}

export default Home
